### PR TITLE
gcp support, ortho optimization, bug fix

### PR DESCRIPTION
**Pull request by dronemapper-io**

### CODE REVIEW

**Comment by dronemapper-io** [comment]
Thx, I was able to test uploading two GCP txt files (3D/2D) along with the images. The images end up in the images folder and both GCP txt files end up in the gcp folder, which works (at least through the NodeMicMac ui). I didn't quite know how to best roll in your GCP changes and just use the single file -- we should discuss a bit and give it some thought @pierotofy

**Comment by pierotofy** [comment]
Uh, I guess it does work (all .txt files are moved to the folder). My bad! :)

We can merge this as-is if you want and discuss the single file implementation at a later day if it works for you.

**Comment by pierotofy** [comment]
Ok, the code changes in https://github.com/OpenDroneMap/ODM/pull/1033/commits/6a678c946170b19a7df5e14f6717988d6999416a should now work correctly with MicMac.

In short, to use the code, you could copy `gcp.py` and `location.py` from the `opendm` folder, make sure you have installed `pyproj` and `GDAL` via `pip` (for Python) and then invoke the GCP code via:

```
from opendm import gcp

gcp_file = gcp.GCPFile('/path/to/gcp_list.txt')
gcp_file.make_micmac_copy('/out/folder', utm_zone='WGS84 UTM 16N')
```

**Comment by dronemapper-io** [comment]
Cool. I will add that code to the project .... it should be easy to support both file formats with this approach.

**Pull request merged**
